{
    "ElementName":"FunctionDefine",
    "actions":{
        "__TYPE":"Array",
        "contents":[
            {
                "ElementName":"FunctionCall",
                "breakPointInfo":{
                    "disabled":false,
                    "hasBreakPoint":false,
                    "type":2
                },
                "caller":{
                    "ElementName":"SourceValue",
                    "breakPointInfo":{
                        "disabled":false,
                        "hasBreakPoint":false,
                        "type":2
                    },
                    "displayName":"",
                    "flags":{
                    },
                    "staticWarningMsgs":{
                        "__TYPE":"Array",
                        "contents":{
                        }
                    },
                    "tips":"",
                    "valueSource":{
                        "ElementName":"Source",
                        "targetUninit":{
                            "id":"Variable:新变量:169328176",
                            "packageName":"__validator__",
                            "s_or_c":"client"
                        }
                    }
                },
                "displayName":"",
                "flags":{
                    "fromOop":true
                },
                "funcSource":{
                    "ElementName":"Source",
                    "targetUninit":{
                        "id":"Class:装备打造面板:1684074892, MethodDefine:更新材料消耗与装备打造栏",
                        "packageName":"p_wbud",
                        "s_or_c":"client"
                    }
                },
                "parameters":{
                    "__TYPE":"Array",
                    "contents":[
                        {
                            "ElementName":"SourceValue",
                            "breakPointInfo":{
                                "disabled":false,
                                "hasBreakPoint":false,
                                "type":2
                            },
                            "displayName":"",
                            "flags":{
                            },
                            "staticWarningMsgs":{
                                "__TYPE":"Array",
                                "contents":{
                                }
                            },
                            "tips":"",
                            "valueSource":{
                                "ElementName":"Source",
                                "targetUninit":{
                                    "id":"Variable:ctrl:3412268007",
                                    "packageName":"__validator__",
                                    "s_or_c":"client"
                                }
                            }
                        }
                    ]
                },
                "staticWarningMsgs":{
                    "__TYPE":"Array",
                    "contents":{
                    }
                },
                "tips":"",
                "typeParameters":{
                    "__TYPE":"Array",
                    "contents":{
                    }
                }
            }
        ]
    },
    "breakPointInfo":{
        "disabled":false,
        "hasBreakPoint":false,
        "type":2
    },
    "defaultResetParameterCount":0,
    "description":"",
    "displayName":"func",
    "flags":{
        "hideConfig":true,
        "noSelf":true,
        "pop":true,
        "unchangeName":true,
        "unchangeParameter":true
    },
    "id":"FunctionDefine:func:714846723",
    "keyword":"",
    "label":"默认",
    "linkspace":"",
    "name":"func",
    "packageName":"__validator__",
    "parameters":{
        "__TYPE":"Array",
        "contents":[
            {
                "ElementName":"Parameter",
                "breakPointInfo":{
                    "disabled":false,
                    "hasBreakPoint":false,
                    "type":2
                },
                "displayName":"ctrl",
                "flags":{
                },
                "id":"Variable:ctrl:3412268007",
                "keyword":"",
                "label":"默认",
                "name":"ctrl",
                "packageName":"__validator__",
                "realType":{
                    "ElementName":"InstanceType",
                    "breakPointInfo":{
                        "disabled":false,
                        "hasBreakPoint":false,
                        "type":2
                    },
                    "displayName":"",
                    "flags":{
                    },
                    "source":{
                        "ElementName":"Source",
                        "targetUninit":{
                            "id":"Class:_OBJ_smallcard_inventory_gui_ctrl_多功能格子",
                            "packageName":"__client__",
                            "s_or_c":"client"
                        }
                    },
                    "staticWarningMsgs":{
                        "__TYPE":"Array",
                        "contents":{
                        }
                    },
                    "tips":"",
                    "typeArgs":{
                        "__TYPE":"Array",
                        "contents":{
                        }
                    }
                },
                "s_or_c":"client",
                "staticWarningMsgs":{
                    "__TYPE":"Array",
                    "contents":{
                    }
                },
                "tips":""
            },
            {
                "ElementName":"Parameter",
                "breakPointInfo":{
                    "disabled":false,
                    "hasBreakPoint":false,
                    "type":2
                },
                "displayName":"mouse_btn_id",
                "flags":{
                },
                "id":"Variable:mouse_btn_id:2268968296",
                "keyword":"",
                "label":"默认",
                "name":"mouse_btn_id",
                "packageName":"__validator__",
                "realType":{
                    "ElementName":"SimpleType",
                    "breakPointInfo":{
                        "disabled":false,
                        "hasBreakPoint":false,
                        "type":2
                    },
                    "displayName":"数值",
                    "flags":{
                    },
                    "name":"number",
                    "staticWarningMsgs":{
                        "__TYPE":"Array",
                        "contents":{
                        }
                    },
                    "tips":""
                },
                "s_or_c":"client",
                "staticWarningMsgs":{
                    "__TYPE":"Array",
                    "contents":{
                    }
                },
                "tips":""
            }
        ]
    },
    "realReturnType":{
        "ElementName":"SimpleType",
        "breakPointInfo":{
            "disabled":false,
            "hasBreakPoint":false,
            "type":2
        },
        "displayName":"void",
        "flags":{
        },
        "name":"void",
        "staticWarningMsgs":{
            "__TYPE":"Array",
            "contents":{
            }
        },
        "tips":""
    },
    "s_or_c":"client",
    "staticWarningMsgs":{
        "__TYPE":"Array",
        "contents":{
        }
    },
    "subsections":{
        "__TYPE":"Array",
        "contents":{
        }
    },
    "tips":"",
    "typeParameters":{
        "__TYPE":"Array",
        "contents":{
        }
    },
    "typeParametersExtends":{
        "__TYPE":"Map",
        "contents":{
        }
    },
    "uiText":"",
    "v2_version":0.900000,
    "variables":{
        "__TYPE":"Array",
        "contents":[
            {
                "ElementName":"Variable",
                "breakPointInfo":{
                    "disabled":false,
                    "hasBreakPoint":false,
                    "type":2
                },
                "defaultValue":{
                    "ElementName":"NewClassFunctionCall",
                    "breakPointInfo":{
                        "disabled":false,
                        "hasBreakPoint":false,
                        "type":2
                    },
                    "caller":{
                        "ElementName":"Instant",
                        "breakPointInfo":{
                            "disabled":false,
                            "hasBreakPoint":false,
                            "type":2
                        },
                        "displayName":"",
                        "flags":{
                        },
                        "staticWarningMsgs":{
                            "__TYPE":"Array",
                            "contents":{
                            }
                        },
                        "tips":"",
                        "type":{
                            "ElementName":"SimpleType",
                            "breakPointInfo":{
                                "disabled":false,
                                "hasBreakPoint":false,
                                "type":2
                            },
                            "displayName":"未定义",
                            "flags":{
                            },
                            "name":"undefined",
                            "staticWarningMsgs":{
                                "__TYPE":"Array",
                                "contents":{
                                }
                            },
                            "tips":""
                        }
                    },
                    "displayName":"",
                    "flags":{
                    },
                    "funcSource":{
                        "ElementName":"Source",
                        "targetUninit":{
                            "id":"Class:装备打造面板:1684074892:Constructor",
                            "packageName":"p_wbud",
                            "s_or_c":"client"
                        }
                    },
                    "parameters":{
                        "__TYPE":"Array",
                        "contents":{
                        }
                    },
                    "staticWarningMsgs":{
                        "__TYPE":"Array",
                        "contents":{
                        }
                    },
                    "tips":"",
                    "typeParameters":{
                        "__TYPE":"Array",
                        "contents":{
                        }
                    }
                },
                "displayName":"新变量",
                "flags":{
                },
                "id":"Variable:新变量:169328176",
                "keyword":"",
                "label":"默认",
                "name":"新变量",
                "packageName":"__validator__",
                "realType":{
                    "ElementName":"InstanceType",
                    "breakPointInfo":{
                        "disabled":false,
                        "hasBreakPoint":false,
                        "type":2
                    },
                    "displayName":"",
                    "flags":{
                    },
                    "source":{
                        "ElementName":"Source",
                        "targetUninit":{
                            "id":"Class:装备打造面板:1684074892",
                            "packageName":"p_wbud",
                            "s_or_c":"client"
                        }
                    },
                    "staticWarningMsgs":{
                        "__TYPE":"Array",
                        "contents":{
                        }
                    },
                    "tips":"",
                    "typeArgs":{
                        "__TYPE":"Array",
                        "contents":{
                        }
                    }
                },
                "s_or_c":"client",
                "staticWarningMsgs":{
                    "__TYPE":"Array",
                    "contents":{
                    }
                },
                "tips":""
            }
        ]
    }
}