{
    "ElementName":"FunctionDefine",
    "actions":{
        "__TYPE":"Array",
        "contents":[
            {
                "ElementName":"If",
                "breakPointInfo":{
                    "disabled":false,
                    "hasBreakPoint":false,
                    "type":2
                },
                "conditions":{
                    "__TYPE":"Array",
                    "contents":[
                        {
                            "ElementName":"FunctionCall",
                            "breakPointInfo":{
                                "disabled":false,
                                "hasBreakPoint":false,
                                "type":2
                            },
                            "displayName":"",
                            "flags":{
                            },
                            "funcSource":{
                                "ElementName":"Source",
                                "targetUninit":{
                                    "id":"FunctionDefine:CompareFunction",
                                    "packageName":"__common__",
                                    "s_or_c":"common"
                                }
                            },
                            "parameters":{
                                "__TYPE":"Array",
                                "contents":[
                                    {
                                        "ElementName":"Instant",
                                        "breakPointInfo":{
                                            "disabled":false,
                                            "hasBreakPoint":false,
                                            "type":2
                                        },
                                        "displayName":"",
                                        "flags":{
                                        },
                                        "staticWarningMsgs":{
                                            "__TYPE":"Array",
                                            "contents":{
                                            }
                                        },
                                        "tips":"",
                                        "type":{
                                            "ElementName":"SimpleType",
                                            "breakPointInfo":{
                                                "disabled":false,
                                                "hasBreakPoint":false,
                                                "type":2
                                            },
                                            "displayName":"字符串",
                                            "flags":{
                                            },
                                            "name":"string",
                                            "staticWarningMsgs":{
                                                "__TYPE":"Array",
                                                "contents":{
                                                }
                                            },
                                            "tips":""
                                        },
                                        "value":"ne"
                                    },
                                    {
                                        "ElementName":"Index",
                                        "baseValue":{
                                            "ElementName":"SourceValue",
                                            "breakPointInfo":{
                                                "disabled":false,
                                                "hasBreakPoint":false,
                                                "type":2
                                            },
                                            "displayName":"",
                                            "flags":{
                                            },
                                            "staticWarningMsgs":{
                                                "__TYPE":"Array",
                                                "contents":{
                                                }
                                            },
                                            "tips":"",
                                            "valueSource":{
                                                "ElementName":"Source",
                                                "targetUninit":{
                                                    "id":"Variable:新变量:2902249133",
                                                    "packageName":"__validator__",
                                                    "s_or_c":"client"
                                                }
                                            }
                                        },
                                        "breakPointInfo":{
                                            "disabled":false,
                                            "hasBreakPoint":false,
                                            "type":2
                                        },
                                        "displayName":"",
                                        "flags":{
                                            "fromOop":true
                                        },
                                        "indexSource":{
                                            "ElementName":"Source",
                                            "targetUninit":{
                                                "id":"Class:_OBJ_smallcard_inventory_gui_ctrl_多功能格子, ClassProperty:bind_item_link",
                                                "packageName":"__client__",
                                                "s_or_c":"client"
                                            }
                                        },
                                        "staticWarningMsgs":{
                                            "__TYPE":"Array",
                                            "contents":{
                                            }
                                        },
                                        "tips":""
                                    },
                                    {
                                        "ElementName":"Instant",
                                        "breakPointInfo":{
                                            "disabled":false,
                                            "hasBreakPoint":false,
                                            "type":2
                                        },
                                        "displayName":"",
                                        "flags":{
                                        },
                                        "staticWarningMsgs":{
                                            "__TYPE":"Array",
                                            "contents":{
                                            }
                                        },
                                        "tips":"",
                                        "type":{
                                            "ElementName":"SimpleType",
                                            "breakPointInfo":{
                                                "disabled":false,
                                                "hasBreakPoint":false,
                                                "type":2
                                            },
                                            "displayName":"未定义",
                                            "flags":{
                                            },
                                            "name":"undefined",
                                            "staticWarningMsgs":{
                                                "__TYPE":"Array",
                                                "contents":{
                                                }
                                            },
                                            "tips":""
                                        }
                                    }
                                ]
                            },
                            "staticWarningMsgs":{
                                "__TYPE":"Array",
                                "contents":{
                                }
                            },
                            "tips":"",
                            "typeParameters":{
                                "__TYPE":"Array",
                                "contents":{
                                }
                            }
                        }
                    ]
                },
                "displayName":"",
                "falseActions":{
                    "__TYPE":"Array",
                    "contents":{
                    }
                },
                "flags":{
                },
                "staticWarningMsgs":{
                    "__TYPE":"Array",
                    "contents":{
                    }
                },
                "tips":"",
                "trueActions":{
                    "__TYPE":"Array",
                    "contents":[
                        {
                            "ElementName":"FunctionCall",
                            "breakPointInfo":{
                                "disabled":false,
                                "hasBreakPoint":false,
                                "type":2
                            },
                            "displayName":"",
                            "flags":{
                            },
                            "funcSource":{
                                "ElementName":"Source",
                                "targetUninit":{
                                    "id":"FunctionDefine:send_custom_event1790050304",
                                    "packageName":"__client__",
                                    "s_or_c":"client"
                                }
                            },
                            "parameters":{
                                "__TYPE":"Array",
                                "contents":[
                                    {
                                        "ElementName":"NewClassFunctionCall",
                                        "breakPointInfo":{
                                            "disabled":false,
                                            "hasBreakPoint":false,
                                            "type":2
                                        },
                                        "caller":{
                                            "ElementName":"Instant",
                                            "breakPointInfo":{
                                                "disabled":false,
                                                "hasBreakPoint":false,
                                                "type":2
                                            },
                                            "displayName":"",
                                            "flags":{
                                            },
                                            "staticWarningMsgs":{
                                                "__TYPE":"Array",
                                                "contents":{
                                                }
                                            },
                                            "tips":"",
                                            "type":{
                                                "ElementName":"SimpleType",
                                                "breakPointInfo":{
                                                    "disabled":false,
                                                    "hasBreakPoint":false,
                                                    "type":2
                                                },
                                                "displayName":"未定义",
                                                "flags":{
                                                },
                                                "name":"undefined",
                                                "staticWarningMsgs":{
                                                    "__TYPE":"Array",
                                                    "contents":{
                                                    }
                                                },
                                                "tips":""
                                            }
                                        },
                                        "displayName":"",
                                        "flags":{
                                        },
                                        "funcSource":{
                                            "ElementName":"Source",
                                            "targetUninit":{
                                                "id":"CustomEvent:请求打造装备:3906312200:Constructor",
                                                "packageName":"p_wbud",
                                                "s_or_c":"client"
                                            }
                                        },
                                        "parameters":{
                                            "__TYPE":"Array",
                                            "contents":[
                                                {
                                                    "ElementName":"SourceValue",
                                                    "breakPointInfo":{
                                                        "disabled":false,
                                                        "hasBreakPoint":false,
                                                        "type":2
                                                    },
                                                    "displayName":"",
                                                    "flags":{
                                                    },
                                                    "staticWarningMsgs":{
                                                        "__TYPE":"Array",
                                                        "contents":{
                                                        }
                                                    },
                                                    "tips":"",
                                                    "valueSource":{
                                                        "ElementName":"Source",
                                                        "targetUninit":{
                                                            "id":"PresetPropertyId:(Preset:游戏247595008, Linkspace:default, PresetKey:游戏)",
                                                            "packageName":"__client__",
                                                            "s_or_c":"client"
                                                        }
                                                    }
                                                },
                                                {
                                                    "ElementName":"Index",
                                                    "baseValue":{
                                                        "ElementName":"SourceValue",
                                                        "breakPointInfo":{
                                                            "disabled":false,
                                                            "hasBreakPoint":false,
                                                            "type":2
                                                        },
                                                        "displayName":"",
                                                        "flags":{
                                                        },
                                                        "staticWarningMsgs":{
                                                            "__TYPE":"Array",
                                                            "contents":{
                                                            }
                                                        },
                                                        "tips":"",
                                                        "valueSource":{
                                                            "ElementName":"Source",
                                                            "targetUninit":{
                                                                "id":"Variable:新变量:2902249133",
                                                                "packageName":"__validator__",
                                                                "s_or_c":"client"
                                                            }
                                                        }
                                                    },
                                                    "breakPointInfo":{
                                                        "disabled":false,
                                                        "hasBreakPoint":false,
                                                        "type":2
                                                    },
                                                    "displayName":"",
                                                    "flags":{
                                                        "fromOop":true
                                                    },
                                                    "indexSource":{
                                                        "ElementName":"Source",
                                                        "targetUninit":{
                                                            "id":"Class:_OBJ_smallcard_inventory_gui_ctrl_多功能格子, ClassProperty:bind_item_link",
                                                            "packageName":"__client__",
                                                            "s_or_c":"client"
                                                        }
                                                    },
                                                    "staticWarningMsgs":{
                                                        "__TYPE":"Array",
                                                        "contents":{
                                                        }
                                                    },
                                                    "tips":""
                                                }
                                            ]
                                        },
                                        "staticWarningMsgs":{
                                            "__TYPE":"Array",
                                            "contents":{
                                            }
                                        },
                                        "tips":"",
                                        "typeParameters":{
                                            "__TYPE":"Array",
                                            "contents":{
                                            }
                                        }
                                    }
                                ]
                            },
                            "staticWarningMsgs":{
                                "__TYPE":"Array",
                                "contents":{
                                }
                            },
                            "tips":"",
                            "typeParameters":{
                                "__TYPE":"Array",
                                "contents":{
                                }
                            }
                        }
                    ]
                }
            }
        ]
    },
    "breakPointInfo":{
        "disabled":false,
        "hasBreakPoint":false,
        "type":2
    },
    "defaultResetParameterCount":0,
    "description":"",
    "displayName":"func",
    "flags":{
        "hideConfig":true,
        "noSelf":true,
        "pop":true,
        "unchangeName":true,
        "unchangeParameter":true
    },
    "id":"FunctionDefine:func:3893927338",
    "keyword":"",
    "label":"默认",
    "linkspace":"",
    "name":"func",
    "packageName":"__validator__",
    "parameters":{
        "__TYPE":"Array",
        "contents":[
            {
                "ElementName":"Parameter",
                "breakPointInfo":{
                    "disabled":false,
                    "hasBreakPoint":false,
                    "type":2
                },
                "displayName":"ctrl",
                "flags":{
                },
                "id":"Variable:ctrl:3969829629",
                "keyword":"",
                "label":"默认",
                "name":"ctrl",
                "packageName":"__validator__",
                "realType":{
                    "ElementName":"InstanceType",
                    "breakPointInfo":{
                        "disabled":false,
                        "hasBreakPoint":false,
                        "type":2
                    },
                    "displayName":"",
                    "flags":{
                    },
                    "source":{
                        "ElementName":"Source",
                        "targetUninit":{
                            "id":"Class:_OBJ_gameui_gui_ctrl_normal_btn",
                            "packageName":"__client__",
                            "s_or_c":"client"
                        }
                    },
                    "staticWarningMsgs":{
                        "__TYPE":"Array",
                        "contents":{
                        }
                    },
                    "tips":"",
                    "typeArgs":{
                        "__TYPE":"Array",
                        "contents":{
                        }
                    }
                },
                "s_or_c":"client",
                "staticWarningMsgs":{
                    "__TYPE":"Array",
                    "contents":{
                    }
                },
                "tips":""
            },
            {
                "ElementName":"Parameter",
                "breakPointInfo":{
                    "disabled":false,
                    "hasBreakPoint":false,
                    "type":2
                },
                "displayName":"mouse_btn_id",
                "flags":{
                },
                "id":"Variable:mouse_btn_id:3159604062",
                "keyword":"",
                "label":"默认",
                "name":"mouse_btn_id",
                "packageName":"__validator__",
                "realType":{
                    "ElementName":"SimpleType",
                    "breakPointInfo":{
                        "disabled":false,
                        "hasBreakPoint":false,
                        "type":2
                    },
                    "displayName":"数值",
                    "flags":{
                    },
                    "name":"number",
                    "staticWarningMsgs":{
                        "__TYPE":"Array",
                        "contents":{
                        }
                    },
                    "tips":""
                },
                "s_or_c":"client",
                "staticWarningMsgs":{
                    "__TYPE":"Array",
                    "contents":{
                    }
                },
                "tips":""
            }
        ]
    },
    "rankOrder":0,
    "realReturnType":{
        "ElementName":"SimpleType",
        "breakPointInfo":{
            "disabled":false,
            "hasBreakPoint":false,
            "type":2
        },
        "displayName":"void",
        "flags":{
        },
        "name":"void",
        "staticWarningMsgs":{
            "__TYPE":"Array",
            "contents":{
            }
        },
        "tips":""
    },
    "s_or_c":"client",
    "staticWarningMsgs":{
        "__TYPE":"Array",
        "contents":{
        }
    },
    "subsections":{
        "__TYPE":"Array",
        "contents":{
        }
    },
    "tips":"",
    "typeParameters":{
        "__TYPE":"Array",
        "contents":{
        }
    },
    "typeParametersExtends":{
        "__TYPE":"Map",
        "contents":{
        }
    },
    "uiText":"",
    "v2_version":0.900000,
    "variables":{
        "__TYPE":"Array",
        "contents":[
            {
                "ElementName":"Variable",
                "breakPointInfo":{
                    "disabled":false,
                    "hasBreakPoint":false,
                    "type":2
                },
                "defaultValue":{
                    "ElementName":"FunctionCall",
                    "breakPointInfo":{
                        "disabled":false,
                        "hasBreakPoint":false,
                        "type":2
                    },
                    "displayName":"",
                    "flags":{
                    },
                    "funcSource":{
                        "ElementName":"Source",
                        "targetUninit":{
                            "id":"FunctionDefine:gui_get_part4248698880.0",
                            "packageName":"__client__",
                            "s_or_c":"client"
                        }
                    },
                    "parameters":{
                        "__TYPE":"Array",
                        "contents":[
                            {
                                "ElementName":"FunctionCall",
                                "breakPointInfo":{
                                    "disabled":false,
                                    "hasBreakPoint":false,
                                    "type":2
                                },
                                "displayName":"",
                                "flags":{
                                    "enableDisplayName":true
                                },
                                "funcSource":{
                                    "ElementName":"Source",
                                    "targetUninit":{
                                        "id":"FunctionDefine:gui_get_main_page1445330944",
                                        "packageName":"__client__",
                                        "s_or_c":"client"
                                    }
                                },
                                "parameters":{
                                    "__TYPE":"Array",
                                    "contents":{
                                    }
                                },
                                "staticWarningMsgs":{
                                    "__TYPE":"Array",
                                    "contents":{
                                    }
                                },
                                "tips":"",
                                "typeParameters":{
                                    "__TYPE":"Array",
                                    "contents":{
                                    }
                                }
                            },
                            {
                                "ElementName":"Instant",
                                "breakPointInfo":{
                                    "disabled":false,
                                    "hasBreakPoint":false,
                                    "type":2
                                },
                                "displayName":"",
                                "flags":{
                                    "enableDisplayName":true
                                },
                                "staticWarningMsgs":{
                                    "__TYPE":"Array",
                                    "contents":{
                                    }
                                },
                                "tips":"",
                                "type":{
                                    "ElementName":"SimpleType",
                                    "breakPointInfo":{
                                        "disabled":false,
                                        "hasBreakPoint":false,
                                        "type":2
                                    },
                                    "displayName":"字符串",
                                    "flags":{
                                    },
                                    "name":"string",
                                    "staticWarningMsgs":{
                                        "__TYPE":"Array",
                                        "contents":{
                                        }
                                    },
                                    "tips":""
                                },
                                "value":"打造装备多功能"
                            }
                        ]
                    },
                    "staticWarningMsgs":{
                        "__TYPE":"Array",
                        "contents":{
                        }
                    },
                    "tips":"",
                    "typeParameters":{
                        "__TYPE":"Array",
                        "contents":[
                            {
                                "ElementName":"InstanceType",
                                "breakPointInfo":{
                                    "disabled":false,
                                    "hasBreakPoint":false,
                                    "type":2
                                },
                                "displayName":"",
                                "flags":{
                                },
                                "source":{
                                    "ElementName":"Source",
                                    "targetUninit":{
                                        "id":"Class:_OBJ_smallcard_inventory_gui_ctrl_多功能格子",
                                        "packageName":"__client__",
                                        "s_or_c":"client"
                                    }
                                },
                                "staticWarningMsgs":{
                                    "__TYPE":"Array",
                                    "contents":{
                                    }
                                },
                                "tips":"",
                                "typeArgs":{
                                    "__TYPE":"Array",
                                    "contents":{
                                    }
                                }
                            }
                        ]
                    }
                },
                "displayName":"新变量",
                "flags":{
                },
                "id":"Variable:新变量:2902249133",
                "keyword":"",
                "label":"默认",
                "name":"新变量",
                "packageName":"__validator__",
                "realType":{
                    "ElementName":"InstanceType",
                    "breakPointInfo":{
                        "disabled":false,
                        "hasBreakPoint":false,
                        "type":2
                    },
                    "displayName":"",
                    "flags":{
                    },
                    "source":{
                        "ElementName":"Source",
                        "targetUninit":{
                            "id":"Class:_OBJ_smallcard_inventory_gui_ctrl_多功能格子",
                            "packageName":"__client__",
                            "s_or_c":"client"
                        }
                    },
                    "staticWarningMsgs":{
                        "__TYPE":"Array",
                        "contents":{
                        }
                    },
                    "tips":"",
                    "typeArgs":{
                        "__TYPE":"Array",
                        "contents":{
                        }
                    }
                },
                "s_or_c":"client",
                "staticWarningMsgs":{
                    "__TYPE":"Array",
                    "contents":{
                    }
                },
                "tips":""
            }
        ]
    }
}